apiVersion: v2
name: varroa
description: A Helm chart for varroa
type: application
version: 2.0.4
appVersion: 1.0.0-2-g4aa32ec
sources:
- https://github.com/NeCTAR-RC/varroa-helm.git
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.29.1
- name: nectarlib
  version: 3.0.1
  repository: oci://registry.rc.nectar.org.au/nectar-helm
- name: mariadb
  version: 20.2.2
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
- name: rabbitmq
  version: 15.2.4
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.rabbitmq
- name: memcached
  version: 7.6.1
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.memcached
