apiVersion: v2
name: varroa
description: A Helm chart for varroa
type: application
version: 2.0.11
appVersion: 1.0.0-9-ga8ac9df
sources:
- https://github.com/NeCTAR-RC/varroa-helm.git
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.30.0
- name: nectarlib
  version: 3.0.3
  repository: oci://registry.rc.nectar.org.au/nectar-helm
- name: mariadb
  version: 20.4.2
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
- name: rabbitmq
  version: 15.5.1
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.rabbitmq
- name: memcached
  version: 7.8.1
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.memcached
