apiVersion: v2
name: varroa
description: A Helm chart for varroa
type: application
version: 1.1.9
appVersion: 0.10.0-8-g909a574
sources:
- https://github.com/NeCTAR-RC/varroa-helm.git
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.23.0
- name: nectarlib
  version: 1.7.8
  repository: oci://registry.rc.nectar.org.au/nectar-helm
- name: mariadb
  version: 19.0.7
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
- name: rabbitmq
  version: 15.0.0
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.rabbitmq
- name: memcached
  version: 7.4.16
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.memcached
